import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        sb: {
          bg: 'var(--sb-bg)',
          bgSoft: 'var(--sb-bg-soft)',
          bgWarm: 'var(--sb-bg-warm)',
          bgGreen: 'var(--sb-bg-green)',
          surface: 'var(--sb-surface)',
          surface2: 'var(--sb-surface-raised)',
          surfaceMuted: 'var(--sb-surface-muted)',
          card: 'var(--sb-card)',
          cardStrong: 'var(--sb-card-strong)',
          inverse: 'var(--sb-inverse)',
          ink: 'var(--sb-ink)',
          inkSoft: 'var(--sb-ink-soft)',
          muted: 'var(--sb-muted)',
          muted2: 'var(--sb-muted-2)',
          placeholder: 'var(--sb-placeholder)',
          line: 'var(--sb-line)',
          lineStrong: 'var(--sb-line-strong)',
          gold: 'var(--sb-solar)',
          goldDark: 'var(--sb-solar-strong)',
          goldSoft: 'var(--sb-solar-soft)',
          goldFaint: 'var(--sb-solar-faint)',
          green: 'var(--sb-green)',
          greenDark: 'var(--sb-green-strong)',
          greenMuted: 'var(--sb-green-soft)',
          orange: 'var(--sb-orange)',
          orangeSoft: 'var(--sb-orange-soft)',
          red: 'var(--sb-red)',
          redSoft: 'var(--sb-red-soft)',
          blue: 'var(--sb-blue)',
          blueSoft: 'var(--sb-blue-soft)',
          purple: 'var(--sb-purple)',
          purpleSoft: 'var(--sb-purple-soft)',
          grey: 'var(--sb-muted)',
          accent: 'var(--sb-bg-green)',
        },
      },
      fontFamily: {
        sans: ['var(--font-app)'],
        heading: ['var(--font-app)'],
        mono: ['var(--font-mono)'],
      },
      borderRadius: {
        'sb-xs': 'var(--sb-radius-xs)',
        'sb-sm': 'var(--sb-radius-sm)',
        'sb-md': 'var(--sb-radius-md)',
        'sb-lg': 'var(--sb-radius-lg)',
        'sb-xl': 'var(--sb-radius-xl)',
        'sb-2xl': 'var(--sb-radius-2xl)',
        'sb-pill': 'var(--sb-radius-pill)',
      },
      boxShadow: {
        'sb-sm': 'var(--sb-shadow-sm)',
        'sb-md': 'var(--sb-shadow-md)',
        'sb-lg': 'var(--sb-shadow-lg)',
        'sb-nav': 'var(--sb-shadow-nav)',
      },
      maxWidth: {
        page: 'var(--sb-page-max)',
        readable: 'var(--sb-readable-max)',
      },
    },
  },
  plugins: [],
}
export default config
